[package]
name = "staking_program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.9"
solana-sdk = "1.9"
spl-token = "3.2"
toml_edit = "0.19.9"

[lib]
crate-type = ["cdylib"]

[features]
default = []